/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MActionSheet: typeof import('./../components/basic/MActionSheet.vue')['default']
    MAvatar: typeof import('./../components/basic/MAvatar.vue')['default']
    MBack: typeof import('./../components/basic/MBack.vue')['default']
    MButton: typeof import('./../components/basic/MButton.vue')['default']
    MCheckTag: typeof import('./../components/basic/MCheckTag.vue')['default']
    MDateRangePicker: typeof import('./../components/basic/MDateRangePicker.vue')['default']
    MDateSelect: typeof import('./../components/basic/MDateSelect.vue')['default']
    MIcon: typeof import('./../components/basic/MIcon.vue')['default']
    MImage: typeof import('./../components/basic/MImage.vue')['default']
    MNavbar: typeof import('./../components/basic/MNavbar.vue')['default']
    MPopup: typeof import('./../components/basic/MPopup.vue')['default']
    MSearchbar: typeof import('./../components/basic/MSearchbar.vue')['default']
    MStatusBar: typeof import('./../components/basic/MStatusBar.vue')['default']
    MTabs: typeof import('./../components/basic/MTabs.vue')['default']
    MTag: typeof import('./../components/basic/MTag.vue')['default']
    MUpload: typeof import('./../components/basic/MUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
